steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_DEPLOY_REGION}-docker.pkg.dev/${_APP_NAME}/my-docker-repo/my-image"
      - "."
    id: Build

  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - ${_DEPLOY_REGION}-${_REPO_URL}/${_APP_NAME}:${_ENVIRONMENT}'
    id: Push

  # Deploy the Docker image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - deploy
      - "${_APP_NAME}-${_ENVIRONMENT}"
      - "--platform=managed"
      - "--image=${_DEPLOY_REGION}-${_REPO_URL}/${_APP_NAME}:${_ENVIRONMENT}"
      - "--region=${_DEPLOY_REGION}"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud

timeout: 1000s
images:
  - "${_DEPLOY_REGION}-${_REPO_URL}/${_APP_NAME}:${_ENVIRONMENT}"
  - "${_DEPLOY_REGION}-${_REPO_URL}/${_APP_NAME}:latest"
options:
  logging: CLOUD_LOGGING_ONLY
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - ${_APP_NAME}-${_ENVIRONMENT}
